name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_puc:
    name: Test on PUC-Rio Lua
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [5.1.5, 5.2.4, 5.3.6, 5.4.3]

    steps:
      - name: Build PUC-Rio Lua ${{ matrix.version }}
        env:
          LUA_VERSION: ${{ matrix.version }}
        run: |
          wget "https://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz"
          tar xzvf "lua-${LUA_VERSION}.tar.gz"
          cd "lua-${LUA_VERSION}"
          make linux SYSLIBS="-Wl,-E -ldl -lreadline" SYSCFLAGS="-DLUA_USE_LINUX -ULUA_COMPAT_5_2 -DLUA_USE_APICHECK"
      - name: Install PUC-Rio Lua ${{ matrix.version }}
        env:
          LUA_VERSION: ${{ matrix.version }}
        run: |
          cd "lua-${LUA_VERSION}"
          sudo make install
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: source .github/install_deps.bash
      - name: Build lgi
        run: |
          make
      - name: Run tests
        run: |
          xvfb-run -a make check LUA_LIB='-llua -ldl -lm'
      - name: Check that make install works
        env:
          LUA_VERSION: ${{ matrix.version }}
        run: source .github/test_make_install.bash

  build_luajit:
    name: Test on LuaJIT
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [2.0.5]

    steps:
      - name: Build LuaJIT ${{ matrix.version }}
        env:
          LUAJIT_VERSION: ${{ matrix.version }}
        run: |
          wget "https://luajit.org/download/LuaJIT-${LUAJIT_VERSION}.tar.gz"
          tar xzvf "LuaJIT-${LUAJIT_VERSION}.tar.gz"
          cd "LuaJIT-${LUAJIT_VERSION}"
          make
      - name: Install LuaJIT ${{ matrix.version }}
        env:
          LUAJIT_VERSION: ${{ matrix.version }}
        run: |
          cd "LuaJIT-${LUAJIT_VERSION}"
          sudo make install
          sudo ln -frs /usr/local/bin/luajit-* /usr/local/bin/lua
          sudo ln -frs /usr/local/lib/libluajit-*.a /usr/local/lib/liblua.a
          sudo ln -frs /usr/local/include/luajit-*/* /usr/local/include/
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: source .github/install_deps.bash
      - name: Build lgi
        run: |
          make
      - name: Run tests
        run: |
          xvfb-run -a make check LUA_LIB='-llua -ldl -lm'
      - name: Check that make install works
        env:
          LUA_VERSION: ${{ matrix.version }}
        run: source .github/test_make_install.bash
